/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectCourseRouteImport } from './routes/select-course'
import { Route as ScoresRouteImport } from './routes/scores'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as OauthCallbackNaverRouteImport } from './routes/oauth/callback/naver'
import { Route as OauthCallbackKakaoRouteImport } from './routes/oauth/callback/kakao'

const SelectCourseRoute = SelectCourseRouteImport.update({
  id: '/select-course',
  path: '/select-course',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresRoute = ScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackNaverRoute = OauthCallbackNaverRouteImport.update({
  id: '/oauth/callback/naver',
  path: '/oauth/callback/naver',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackKakaoRoute = OauthCallbackKakaoRouteImport.update({
  id: '/oauth/callback/kakao',
  path: '/oauth/callback/kakao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scores': typeof ScoresRoute
  '/select-course': typeof SelectCourseRoute
  '/admin/users': typeof AdminUsersRoute
  '/oauth/callback/kakao': typeof OauthCallbackKakaoRoute
  '/oauth/callback/naver': typeof OauthCallbackNaverRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scores': typeof ScoresRoute
  '/select-course': typeof SelectCourseRoute
  '/admin/users': typeof AdminUsersRoute
  '/oauth/callback/kakao': typeof OauthCallbackKakaoRoute
  '/oauth/callback/naver': typeof OauthCallbackNaverRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scores': typeof ScoresRoute
  '/select-course': typeof SelectCourseRoute
  '/admin/users': typeof AdminUsersRoute
  '/oauth/callback/kakao': typeof OauthCallbackKakaoRoute
  '/oauth/callback/naver': typeof OauthCallbackNaverRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/scores'
    | '/select-course'
    | '/admin/users'
    | '/oauth/callback/kakao'
    | '/oauth/callback/naver'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/scores'
    | '/select-course'
    | '/admin/users'
    | '/oauth/callback/kakao'
    | '/oauth/callback/naver'
  id:
    | '__root__'
    | '/'
    | '/scores'
    | '/select-course'
    | '/admin/users'
    | '/oauth/callback/kakao'
    | '/oauth/callback/naver'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScoresRoute: typeof ScoresRoute
  SelectCourseRoute: typeof SelectCourseRoute
  AdminUsersRoute: typeof AdminUsersRoute
  OauthCallbackKakaoRoute: typeof OauthCallbackKakaoRoute
  OauthCallbackNaverRoute: typeof OauthCallbackNaverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-course': {
      id: '/select-course'
      path: '/select-course'
      fullPath: '/select-course'
      preLoaderRoute: typeof SelectCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback/naver': {
      id: '/oauth/callback/naver'
      path: '/oauth/callback/naver'
      fullPath: '/oauth/callback/naver'
      preLoaderRoute: typeof OauthCallbackNaverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback/kakao': {
      id: '/oauth/callback/kakao'
      path: '/oauth/callback/kakao'
      fullPath: '/oauth/callback/kakao'
      preLoaderRoute: typeof OauthCallbackKakaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScoresRoute: ScoresRoute,
  SelectCourseRoute: SelectCourseRoute,
  AdminUsersRoute: AdminUsersRoute,
  OauthCallbackKakaoRoute: OauthCallbackKakaoRoute,
  OauthCallbackNaverRoute: OauthCallbackNaverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
